fix wrongly defined define HAVE_STDLIB_H
when change build system from autotools to cmake, below
part is replace wrongly:

"#undef HAVE_STDLIB_H"
should be change to "#cmakedefine HAVE_STDLIB_H 1"
not "#cmakedefine HAVE_STDLIB_H"

otherwise, even if stdlib.h is found, output file
of configure_file() will define like: #define HAVE_STDLIB_H
but we need it as #define HAVE_STDLIB_H 1, since for
different defination of HAVE_STDLIB_H will cause below error:
error: "HAVE_STDLIB_H" redefined [-Werror]

Signed-off-by: Changqing Li <changqing.li@windriver.com>